config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :walks do
    resources :arrivals, only: [:index], :to => 'walks/arrivals#index'
  end
  resources :arrivals, except: [:new] do
    resource :report, only: %i(show), controller: "arrivals/report"
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:destroy]
  devise_scope :user do
    post 'logout', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  # 以下の2つのルーティングはURLの修正に伴いリダイレクトさせているが、後に削除する
  scope module: 'tmp' do
    resources :users, only: [] do
      resources :arrivals, only: :index
    end
    get '/walk', to: 'walks#show'
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/arrival.rb
# frozen_string_literal: true

class Arrival < ApplicationRecord
  belongs_to :walk
  belongs_to :station
  before_save :convert_nil_to_blank
  before_update :add_space_after_url
  validates :arrived_at, presence: true
  validates :memo, length: { maximum: 250 }, allow_blank: true # DBの制限は255字だが、リンクでスペースを生成する場合があるため250に設定
  validate :prohibit_arrival_without_next_station, on: :create
  validate :arrivals_count_must_be_within_limit, on: :create
  validate :check_arrived_time, on: :update
  before_save :truncate_seconds_of_arrived_time
  before_destroy :check_arrival_location, unless: -> { destroyed_by_association }

  private

  def check_arrived_time
    errors.add :arrived_at, 'に未来の時刻は設定できません' if arrival_time_is_later_than_current?
    errors.add :arrived_at, 'は、一つ前の到着時刻より後、一つ後ろの到着時間より前の時刻を設定してください' if arrival_time_is_outside_of_range?
  end

  def arrival_time_is_later_than_current?
    Time.current < arrived_at
  end

  def arrival_time_is_outside_of_range?
    arrivals = Arrival.where(walk:).order(:created_at)
    self_index = arrivals.find_index(self)
    next_arrival_time = self == arrivals.last ? nil : arrivals[self_index + 1].arrived_at
    prev_arrival_time = self == arrivals.first ? nil : arrivals[self_index - 1].arrived_at
    !(prev_arrival_time..next_arrival_time).cover? arrived_at
  end

  def prohibit_arrival_without_next_station
    arrival_last = Arrival.includes(:station).where(walk:).order(:created_at).last
    return unless arrival_last

    current_station = arrival_last.station
    is_correct_next_station =
      if walk.clockwise
        current_station.clockwise_next_station == station
      else
        Station.find_by(clockwise_next_station: current_station) == station
      end
    return if is_correct_next_station

    errors.add :station_id, '隣駅以外に到着することはできません'
  end

  def convert_nil_to_blank
    self.memo = '' if memo.nil?
  end

  def add_space_after_url
    urls = URI.extract(memo)
    return if urls.empty?

    urls.each do |url|
      memo.gsub!(/#{url}(?!\s)/, "#{url} ") # rinku gemでURLの切れ目が正しく判定できない場合があるため、空白を追加
    end
  end

  def check_arrival_location
    return if self == walk.arrivals.order(:created_at).last

    errors.add :base, '最後の到着以外は削除できません'
    throw(:abort)
  end

  def truncate_seconds_of_arrived_time
    self.arrived_at = arrived_at.beginning_of_minute
  end

  def arrivals_count_must_be_within_limit
    errors.add(:base, '駅の数以上の到着記録は作成できません') if walk.arrivals.count > Station.cache_count
  end
end

app/controllers/arrivals/report_controller.rb
# frozen_string_literal: true

class Arrivals::ReportController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @arrival = Arrival.find(params[:arrival_id])
    @walk = @arrival.walk
  end
end

app/controllers/arrivals_controller.rb
# frozen_string_literal: true

class ArrivalsController < ApplicationController
  before_action :set_walk, only: %i[index show]
  before_action :set_arrival, only: %i[show edit update destroy]
  before_action :set_user, only: %i[index]

  def index
    @arrivals = current_walk.arrivals.order(:created_at).includes(:station)
  end

  def show
    @station = @arrival.station
    @arrived_distance = @walk.arrived_distance
    @number_of_walked = @walk.number_of_walked
  end

  def edit; end

  def create
    @arrival = current_walk.arrivals.new(**arrival_params, arrived_at: Time.current)
    if @arrival.save
      redirect_to @arrival
    else
      redirect_to walk_path(current_walk), alert: '到着記録を保存できませんでした。'
    end
  end

  def update
    @arrival.assign_attributes(arrival_params)
    return unless @arrival.changed?

    if @arrival.save
      flash.now.notice = '到着記録を更新しました。'
    else
      render 'edit', status: :unprocessable_content
    end
  end

  def destroy
    redirect_to arrivals_path if @arrival.destroy
  end

  private

  def set_arrival
    @arrival = current_user.arrivals.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def set_walk
    @walk = current_walk

    return if @walk

    redirect_to root_path, alert: '歩行記録が存在しません。'
  end

  def arrival_params
    params.require(:arrival).permit(:station_id, :arrived_at, :memo)
  end
end

app/controllers/temp/arrivals_controller.rb
# frozen_string_literal: true

class Temp::ArrivalsController < ApplicationController
  skip_before_action :authenticate_user!
  # URL変更のため一時的に定義しているが、後に削除する

  def index
    user = User.find(params[:user_id])
    walk = user.walks.order(:created_at).first!
    redirect_to walk_arrivals_url(walk)
  end
end

app/controllers/users/arrivals_controller.rb
# frozen_string_literal: true

class Users::ArrivalsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_walk, only: %i[index]

  def index
    if @walk.publish || current_user == @walk.user
      @arrivals = @walk.arrivals.order(:created_at).includes(:station)
      @user = current_user
      render 'arrivals/index'
    else
      redirect_to root_path, notice: 'この到着記録は非公開です'
    end
  end

  private

  def set_walk
    user = User.find(params[:user_id])
    @walk = user.walk

    return if @walk

    redirect_to root_path, alert: '歩行記録が存在しません。'
  end
end

app/controllers/walks/arrivals_controller.rb
# frozen_string_literal: true

class Walks::ArrivalsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_walk, only: %i[index]

  def index
    if @walk.publish
      @arrivals = @walk.arrivals.order(:created_at).includes(:station)
      @user = current_user
      render 'arrivals/index'
    else
      redirect_to root_path, notice: 'この到着記録は非公開です'
    end
  end

  private

  def set_walk
    @walk = Walk.find(params[:walk_id])

    return if @walk

    redirect_to root_path, alert: '歩行記録が存在しません。'
  end
end

app/helpers/arrivals_helper.rb
# frozen_string_literal: true

module ArrivalsHelper
  def remaining_distance(arrived_distance:)
    (Station.total_distance - arrived_distance).round(2)
  end

  def number_of_remaining(number_of_walked:)
    Station.cache_count - number_of_walked
  end

  def deletable?(editable:, arrival:, arrivals:)
    editable && arrival == arrivals.last && arrival != arrivals.first
  end
end

app/views/arrivals/_arrival.html.slim
- # rubocop:disable Rails/OutputSafety
= turbo_frame_tag arrival do
  .ml-16.border-l-8.pl-4.pb-6.border-lime-500.relative
    .h-4.w-4.bg-white.border.border-lime-500.absolute.-left-3.top-3.rounded-full
    .mb-2
      .flex.items-center.py-2
        span.-ml-24.pl-2.mr-9.text-xl.w-16
          | #{l arrival.arrived_at, format: :without_date}
        - if arrival == arrivals.first
          p.bg-yamanote-green-150.text-white.px-2.py-1.mr-1.rounded-lg.text-sm 出発
        - elsif arrival == arrivals.last && arrival.walk.finished?
          p.bg-yamanote-green-150.text-white.px-2.py-1.mr-1.rounded-lg.text-sm ゴール
        p.text-xl
          | #{arrival.station.name}駅
      - if arrival.memo.present?
        #arrival_memo.text-sm.text-zinc-500.break-all.ml-1
          / XSSが起きないことを確認の上、slimlintから除外
          = raw Rinku.auto_link(simple_format(h(arrival.memo)), :all, 'target="_blank"')
    - if arrival.walk.user == current_user
      = link_to edit_walk_arrival_path(walk_id: arrival.walk.id, id: arrival.id), class: 'inline-block h-11 content-center' do
        .text-sm.h-8.link-important 編集
      - if deletable?(editable:, arrival:, arrivals:)
        = link_to '到着を削除する',
                  walk_arrival_path(walk_id: arrival.walk.id, id: arrival.id),
                  class: 'text-sm text-gray-400 underline pl-4 hover:text-black',
                  data: { turbo_frame: 'arrivals-list', turbo_method: 'delete', turbo_confirm: '本当に削除しますか？' }
- # rubocop:enable Rails/OutputSafety

app/views/arrivals/_arrived.html.slim
h2.text-xl.font-bold.mb-4 #{station.name}駅に到着🎉

= image_tag station_image_path(station:),
            class: 'md:max-w-40 md:max-h-40 max-h-32 max-w-32 mx-auto',
            width: "200", height: "200",
            alt: "#{station.name}駅のイラスト"

p.mt-2
  | 歩いた駅は#{number_of_walked}駅（残り#{number_of_remaining}駅）、
  br
  | 歩いた距離は約#{arrived_distance}kmです！

app/views/arrivals/_finished.html.slim
.border.border-4.border-bright-orange-50.m-2.p-6.text-center
  h2.py-2.text-2xl.font-extrabold 表彰状
  .text-sm.md:text-base.text-left
    p.my-1 あなたは、山手線の#{Station.cache_count}駅全てを歩ききりました。
    p.my-1 都会の過酷な条件下で、身体の疲れや足の痛みやにも負けず、精力的に歩き続けたことは、見る人に深い感動を与えました。
    p.my-1 よってここに、その不屈の精神と絶え間ない努力を称え、表彰します。
  table.mt-6.mx-auto.text-sm.border.border-gray-400 data-controller="time" data-time-departure-date-value="#{walk.created_at.iso8601}"
    tr
      th.font-normal.bg-yamanote-green-50.px-3.md:px-4 出発時刻
      td.py-1.px-3.md:px-4
        | #{l arrival_of_departure.arrived_at}
    tr
      th.font-normal.bg-yamanote-green-50.px-3.md:px-4 ゴール時刻
      td.py-1.px-3.md:px-4 #{l arrival_of_goal.arrived_at}
    tr
      th.font-normal.bg-yamanote-green-50.px-3.md:px-4 かかった時間
      td.py-1.px-3.md:px-4 #{time_to_reach_goal}

app/views/arrivals/edit.html.slim
= turbo_frame_tag @arrival
  = render 'shared/errors', model: @arrival
  = form_with model: @arrival, method: :put do |f|
    = f.label :arrived_at, class: 'inline-block mt-4 mb-1'
    .flex.items-center
      = f.time_select :arrived_at, {}, { class: 'rounded-sm border border-gray-300' }
      p.ml-2.text-xl
        | #{@arrival.station.name}駅
    = f.label :memo, class: 'inline-block mt-4 mb-1'
    = f.text_area :memo, class: 'inline w-full rounded-sm border border-gray-300', placeholder: '辛くなってきた！自転車が羨ましい><', maxlength: 250, autofocus: true
    .text-center.my-2
      = f.submit '保存', class: 'btn-primary'

app/views/arrivals/index.html.slim
- title '到着一覧'
- set_meta_tags description: '到着記録の一覧ページです。'
- editable = @walk.user == @user

.py-4
  .flex
    h2.text-2xl.font-bold.inline-block 到着履歴
    .ml-auto
      - if editable
        .flex.justify-end
          span.pr-2 #{@walk.publish ? '公開' : '非公開'}
          = form_with model: @walk, class: 'inline-block', method: :patch do |f|
            = f.label :publish
              = f.check_box :publish, { class: 'sr-only peer', onchange: 'this.form.requestSubmit()' }, 'true', 'false'
              .toggle-switch.cursor-pointer
        - if !@walk.publish
          p.text-xs.text-gray-500
            | 公開をONにすると到着履歴の
            br
            | URLを他の人とシェアできます。
  - if editable && @walk.publish
    .flex.items-center.mt-4
      label.text-xs.pr-1 for='url' URL
      = text_field_tag 'url', walk_arrivals_url(@walk), { readonly: true, class: 'border border-gray-300 text-gray-900 rounded-lg text-sm grow' }
      = button_tag data: { controller: 'clipboard', action: 'clipboard#copy', clipboard_url_value: walk_arrivals_url(@walk) }, class: 'inline-block hover:bg-gray-100 p-2', id: 'copy_button'
        i class='fa-regular fa-copy fa-xl'
= turbo_frame_tag 'arrivals-list' do
  = render partial: 'arrivals/arrival', collection: @arrivals, as: :arrival, locals: { user: @user, arrivals: @arrivals, editable: }

- if editable
  .text-center.my-4
    = link_to '地図に戻る', walk_path(current_walk), class: 'link-important'

app/views/arrivals/show.html.slim
ruby:
  if @walk.finished?
    title "#{@station.name}駅にゴール"
    set_meta_tags description: '一周の表彰ページです'
    finish = true
    time_to_reach_goal = time_to_reach_goal(@walk)
    text_for_post = "【山手線を徒歩で一周に挑戦中】%0a山手線#{Station.cache_count}駅全てを歩ききりました🎉🎉かかった時間は#{time_to_reach_goal}でした！"
  else
    title "#{@station.name}駅に到着"
    set_meta_tags description: "#{@station.name}駅に到着の詳細ページです。"
    number_of_remaining = number_of_remaining(number_of_walked: @number_of_walked)
    text_for_post = "【山手線を徒歩で一周に挑戦中】%0a#{@station.name}駅に到着しました🎉歩いた駅は#{@number_of_walked}駅（残り#{number_of_remaining}駅）、歩いた距離は約#{@arrived_distance}kmです！"
  end

.my-8.md:my-12.mx-auto.px-4.text-lg.text-center.md:w-2/3
  - if finish
    = render partial: 'finished', locals: { walk: @walk, arrival_of_departure: @walk.arrival_of_departure, arrival_of_goal: @walk.arrival_of_goal, time_to_reach_goal: }
  - else
    = render partial: 'arrived', locals: { station: @station, number_of_walked: @number_of_walked, number_of_remaining:, arrived_distance: @arrived_distance }
  .mt-4 data-controller='modal'
    button#memo_modal_button.link-important.w-44 data-action='modal#open'
      | メモを追加
    = render partial: 'dialogs/memo', locals: { arrival: @arrival }
  .m-4
    = render partial: 'shared/post_button', locals: { text: text_for_post, url: arrival_report_url(@arrival) }
  .mt-8
    = link_to '地図に戻る', walk_path(current_walk), class: 'link-important w-44'

app/views/arrivals/update.turbo_stream.slim
= turbo_stream.replace @arrival, locals: { arrival: @arrival, arrivals: @arrival.walk.arrivals, editable: true }, partial: 'arrivals/arrival'
= turbo_stream.update 'flash', partial: 'layouts/flash'