config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :walks do
    resources :arrivals, only: [:index], :to => 'walks/arrivals#index'
  end
  resources :arrivals, except: [:new] do
    resource :report, only: %i(show), controller: "arrivals/report"
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:destroy]
  devise_scope :user do
    post 'logout', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  # 以下の2つのルーティングはURLの修正に伴いリダイレクトさせているが、後に削除する
  scope module: 'tmp' do
    resources :users, only: [] do
      resources :arrivals, only: :index
    end
    get '/walk', to: 'walks#show'
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/views/dialogs/_caution.html.slim
dialog class='p-4 w-[640px] rounded-lg backdrop:bg-black/80 relative transition-all duration-1000 ease-in-out' data-caution-target='dialog'
  h2.text-2xl.font-bold.text-center.my-4.mx-auto 山手線一周の注意
  ol.list-disc.pl-6.leading-8
    li.mb-2
      | 山手線を徒歩で一周するには、約12時間かかります。
      br
      | 体調管理には十分注意し、無理をしないようにしてください。また、気温が高い日や悪天候の日の歩行は控えてください。
    li.mb-2
      | アプリ使用時は、立ち止まって操作してください。
    li.mb-2
      = link_to 'https://scrapbox.io/yamanotes/%E5%B1%B1%E6%89%8B%E7%B7%9A%E5%BE%92%E6%AD%A9%E4%B8%80%E5%91%A8%E3%81%AE%E6%BA%96%E5%82%99%E3%83%AA%E3%82%B9%E3%83%88',
        class: 'underline text-blue-600 hover:text-gray-400', target: '_blank', rel: 'noopener'
        | 山手線一周の準備リスト
      p.inline ・
      = link_to 'https://scrapbox.io/yamanotes/%E5%B1%B1%E6%89%8B%E7%B7%9A%E4%B8%80%E5%91%A8%E3%81%AE%E6%B3%A8%E6%84%8F',
        class: 'underline text-blue-600 hover:text-gray-400', target: '_blank', rel: 'noopener'
        | 歩行上の注意
      | を確認してください。
    li.mb-2
      | 怪我や事故などが発生した場合、開発者は一切の責任を負いかねます。
  button.block.link-important.mx-auto.outline-none.mt-4.mb-2 data-action="click->caution#close" autofocus=true 確認しました

app/views/dialogs/_help.html.slim
dialog class='p-4 w-[640px] rounded-lg backdrop:bg-black/80 relative' data-modal-target='dialog'
  h2.text-2xl.font-bold.text-center.my-2.mx-auto 使い方
  button.focus:outline-none.absolute.top-0.right-0.p-2.m-2.hover:bg-gray-100 data-action="click->modal#close" autofocus=true
    i.fa-solid.fa-xmark.fa-2xl
  ol.list-disc.pl-6.leading-8
    li.mb-2
      | 駅に着いたら
      button.btn-primary.inline-block.mx-1
        | 到着
      | ボタンを押しましょう。
    li.mb-2
      a.link-important.mx-1
        | メモ
      | ボタンから、各駅のメモを追加できます。
    li.mb-2
      | 記録を間違った時は、
      = link_to '到着一覧ページ', walk_arrivals_path(current_walk&.id), class: 'text-blue-600 underline hover:text-gray-400'
      | から編集・削除できます。
    li.mb-2
      | スタート時刻や内回り・外回りなどの設定を変えたいときは、メニューの「リタイアする」から一度データを削除してください。
    li.mb-2
      p.inline 歩行の際は、
      = link_to 'https://scrapbox.io/yamanotes/%E5%B1%B1%E6%89%8B%E7%B7%9A%E5%BE%92%E6%AD%A9%E4%B8%80%E5%91%A8%E3%81%AE%E6%BA%96%E5%82%99%E3%83%AA%E3%82%B9%E3%83%88',
        class: 'text-blue-600 underline hover:text-gray-400', target: '_blank', rel: 'noopener'
        | 山手線一周の準備リスト
      p.inline ・
      = link_to 'https://scrapbox.io/yamanotes/%E5%B1%B1%E6%89%8B%E7%B7%9A%E4%B8%80%E5%91%A8%E3%81%AE%E6%B3%A8%E6%84%8F',
        class: 'text-blue-600 underline hover:text-gray-400', target: '_blank', rel: 'noopener'
        | 歩行上の注意
      | を参考にしてください。

app/views/dialogs/_memo.html.slim
dialog class='p-4 w-[640px] rounded-lg backdrop:bg-black/80 relative' data-modal-target='dialog'
  h2.text-2xl.font-bold.text-center.my-2.mx-auto メモを追加
  button.focus:outline-none.absolute.top-0.right-0.p-2.m-2.hover:bg-gray-100 data-action="click->modal#close" autofocus=true
    i.fa-solid.fa-xmark.fa-2xl
  = form_with model: arrival, url: walk_arrival_path(walk_id: current_walk, id: arrival.id) do |form|
    = form.text_area :memo, rows: '6', class: 'w-full  text-base rounded-lg', placeholder: '辛くなってきた！自転車が羨ましい><', autofocus: true, maxlength: '250'
    = form.submit '保存', class: 'block btn-primary mx-auto mt-2', data: { action: 'click->modal#close' }

app/views/dialogs/_menu.html.slim
dialog data-slideover-target='dialog' class='h-full max-h-full w-[640px] max-w-full my-0 mx-auto bg-transparent slideover'
  ul.p-8.bg-lime-50.h-full.w-56.md:w-72
    - if current_walk
      li = link_to 'ダッシュボード', walk_path(current_walk), class: 'inline-block w-full hover:bg-lime-100 py-2 px-4 focus:outline-hidden', autofocus: true
      li = link_to '到着一覧', arrivals_path, class: 'inline-block w-full hover:bg-lime-100 py-2 px-4'
      li = link_to 'リタイアする', walk_path(current_walk), data: { turbo_method: :delete, turbo_confirm: '歩行データはすべて削除されます。よろしいですか？' },
                                                          class: 'inline-block w-full hover:bg-lime-100 py-2 px-4'
    li = link_to '退会する', user_path(current_user), data: { turbo_method: :delete, turbo_confirm: 'データをすべて削除して退会します。よろしいですか？' }, class: 'inline-block w-full hover:bg-lime-100 py-2 px-4'
    li = link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :post }, class: 'inline-block w-full hover:bg-lime-100 py-2 px-4'
    li = link_to 'トップページ', root_path, class: 'inline-block w-full hover:bg-lime-100 py-2 px-4'