config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :walks do
    resources :arrivals, only: [:index], :to => 'walks/arrivals#index'
  end
  resources :arrivals, except: [:new] do
    resource :report, only: %i(show), controller: "arrivals/report"
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:destroy]
  devise_scope :user do
    post 'logout', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  # 以下の2つのルーティングはURLの修正に伴いリダイレクトさせているが、後に削除する
  scope module: 'tmp' do
    resources :users, only: [] do
      resources :arrivals, only: :index
    end
    get '/walk', to: 'walks#show'
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/walk.rb
# frozen_string_literal: true

class Walk < ApplicationRecord
  belongs_to :user
  has_many :arrivals, dependent: :destroy
  has_many :stations, through: :arrivals
  validates :clockwise, inclusion: { in: [true, false] }
  validate :active_walk_uniqueness, on: :create

  def current_station
    arrivals.includes(:station).order(:created_at).last&.station
  end

  def arrived_stations
    arrivals.order(:created_at).includes(:station).map(&:station)
  end

  def arrived_distance
    if finished?
      Station.total_distance
    else
      exclude_station_id = clockwise ? arrivals.order(:created_at).last&.station_id : arrivals.order(:created_at).first&.station_id
      distance_list = arrivals.joins(:station).where.not(station_id: exclude_station_id).pluck('stations.clockwise_distance_to_next')
      distance_list.sum.round(2)
    end
  end

  def arrival_of_departure
    arrivals.order(:created_at)&.first
  end

  def arrival_of_goal
    arrivals.order(:created_at).last if finished?
  end

  def number_of_walked
    arrivals.count - 1
  end

  def finished?
    arrivals.count > Station.cache_count
  end

  private

  def active_walk_uniqueness
    # TODO: 後ほど active な walk のみを対象に限定する
    return if user.walks.empty?

    errors.add(:user_id, '一人につき、実施中の歩行記録は一つしか作成できません')
  end
end

app/controllers/temp/walks_controller.rb
# frozen_string_literal: true

class Temp::WalksController < ApplicationController
  # URL変更のため一時的に定義しているが、後に削除する
  def show
    redirect_to current_walk
  end
end

app/controllers/walks/arrivals_controller.rb
# frozen_string_literal: true

class Walks::ArrivalsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_walk, only: %i[index]

  def index
    if @walk.publish
      @arrivals = @walk.arrivals.order(:created_at).includes(:station)
      @user = current_user
      render 'arrivals/index'
    else
      redirect_to root_path, notice: 'この到着記録は非公開です'
    end
  end

  private

  def set_walk
    @walk = Walk.find(params[:walk_id])

    return if @walk

    redirect_to root_path, alert: '歩行記録が存在しません。'
  end
end

app/controllers/walks_controller.rb
# frozen_string_literal: true

class WalksController < ApplicationController
  before_action :set_walk, only: %i[show destroy]
  before_action :set_maptiler_key, only: %i[show]
  before_action :redirect_if_walk_not_exist, only: %i[show]

  def show
    @arrival = Arrival.new
    @arrivals = @walk.arrivals.order(:created_at).pluck(:station_id)
    @station = @walk.current_station
    @arrived_distance = @walk.arrived_distance
    @number_of_walked = @walk.number_of_walked
  end

  def new
    @walk = Walk.new
    @arrival = @walk.arrivals.new
  end

  def create
    walk = Walk.new(**walk_params, user: current_user)
    if walk.invalid?
      redirect_to walk_path(current_walk), alert: walk.errors.full_messages.join
      return
    end

    walk.transaction do
      walk.save!
      walk.arrivals.create!(**arrival_params, arrived_at: Time.current)
    end
    redirect_to walk_path(walk), notice: '歩行記録ノートを作成しました。'
  end

  def update
    return unless current_walk.update(walk_params)

    redirect_to arrivals_path, notice: current_walk.publish ? '到着履歴を公開しました。URLで到着履歴を共有しましょう。' : '到着履歴を非公開にしました。'
  end

  def destroy
    ActiveRecord::Base.transaction do
      # N+1 が発生するため、arrivalを先に削除する
      # 最後の到着駅以外は削除できないバリデーションがあるため、`delete_all`にしている
      @walk.arrivals.delete_all
      @walk.destroy!
    end
    redirect_to new_walk_path, notice: '歩行記録ノートを削除しました。'
  end

  private

  def redirect_if_walk_not_exist
    return unless current_walk.nil?

    redirect_to new_walk_path
  end

  def walk_params
    params.require(:walk).permit(:clockwise, :publish)
  end

  def arrival_params
    params.require(:arrival).permit(:station_id, :arrived_at, :memo)
  end

  def set_walk
    @walk = current_user.walks.find(params[:id])
  end

  def set_maptiler_key
    gon.maptiler_key = ENV.fetch('MAPTAILER_KEY', nil)
  end
end

app/helpers/walks_helper.rb
# frozen_string_literal: true

module WalksHelper
  def elapsed_time(walk)
    elapsed_seconds = Time.current - walk.arrival_of_departure.arrived_at
    convert_to_local_time(elapsed_seconds)
  end

  def time_to_reach_goal(walk)
    return unless walk.finished?

    convert_to_local_time(walk.arrival_of_goal.arrived_at - walk.arrival_of_departure.arrived_at)
  end

  private

  def convert_to_local_time(m_seconds)
    hours = (m_seconds / 3600).to_i
    minutes = ((m_seconds - (hours * 3600)) / 60).to_i
    "#{hours}時間#{minutes.to_i}分"
  end
end

app/views/walks/_walk.html.slim
.w-3/4.my-4.mx-auto
  #before_station.flex.items-center
    span.mr-2 前の駅:
    span.font-bold.text-lg.max-w-28.md:max-w-full #{current_station.name}駅
    .ml-auto data-controller="modal"
      button#memo_modal_button.link-important.px-6 data-action="modal#open"
        | メモ
      = render partial: 'dialogs/memo', locals: { arrival: walk.arrivals.order(:created_at).last }
  .text-center.my-1
    i.fa-solid.fa-arrow-down.pr-2
    span #{current_station.distance_to_next(clockwise: walk.clockwise)}km
  #next_station.flex.items-center
    span.mr-2 次の駅:
    span.font-bold.text-lg.max-w-28.md:max-w-full #{current_station.next(clockwise: walk.clockwise).name}駅
    = form_with model: arrival, url:  walk_arrivals_path(current_walk), class: 'ml-auto' do |f|
      = f.hidden_field :station_id, value: current_station.next(clockwise: walk.clockwise).id
      = f.submit '到着', class: 'px-6 btn-primary'

app/views/walks/new.html.slim
- title '一周の設定'
- set_meta_tags description: '一周の設定をするページです'

h2.text-lg.mt-10.mb-2.text-center YamaNotesへようこそ！
.mb-10.mx-auto.py-8.px-6.border-4.text-lg.text-center.md:w-2/3 data-controller="pagination introduction" data-pagination-total-pages-value="3" data-pagination-current-page-value="1"
  .text-center.my-0.mx-auto data-controller='clockwise' data-clockwise-true-path-value="#{asset_path('clockwise.png')}" data-clockwise-false-path-value="#{asset_path('counter_clockwise.png')}"
    = form_with model: [@walk, @arrival], url: walks_path, method: :post do |f|
      = render partial: 'walks/new/page1', locals: { f: }
      = render partial: 'walks/new/page2', locals: { f: }
      = render partial: 'walks/new/page3', locals: { f: }

app/views/walks/show.html.slim
- title 'ダッシュボード'
- set_meta_tags description: '現在の一周の状態が表示される画面です。'

div data-controller='caution'
  = render partial: 'dialogs/caution'
= render 'shared/errors', model: @arrival
- if @walk.finished?
  .my-4
    p おめでとうございます🎉
    p #{Station.cache_count}駅全てを歩ききりました！
    .flex.items-center.justify-center.my-4
      = link_to '記録を見る', @walk.arrival_of_goal, class: 'mx-4 text-blue-600 hover:underline'
      = link_to '初めから歩く', walk_path(current_walk), data: { turbo_method: :delete, turbo_confirm: '歩行データはすべて削除されます。よろしいですか？' }, class: 'mx-4 link-important'
- else
  = render partial: 'walk', locals: { walk: @walk, arrival: @arrival, current_station: @station }
= render partial: 'shared/map', locals: { current_station: @station, station_ids: @arrivals }
.my-4.text-center
  h2.font-bold.mb-2 ここまでの記録
  table.mb-4.mx-auto data-controller="time" data-time-departure-date-value="#{@walk.arrival_of_departure.arrived_at.iso8601}"
    tr
      th.border.border-gray-400.font-normal.bg-yamanote-green-80.text-right.px-4.py-1 出発から
      td.border.border-gray-400.text-left.px-4.py-1 data-time-target="elapsed"
        | #{elapsed_time(@walk)}
    tr
      th.border.border-gray-400.font-normal.bg-yamanote-green-80.text-right.px-4.py-1 歩いた駅
      td.border.border-gray-400.text-left.px-4.py-1 #{@number_of_walked}駅(残り#{number_of_remaining(number_of_walked: @number_of_walked)}駅)
    tr
      th.border.border-gray-400.font-normal.bg-yamanote-green-80.text-right.px-4.py-1 歩いた距離
      td.border.border-gray-400.text-left.px-4.py-1 約#{@arrived_distance}km(残り約#{remaining_distance(arrived_distance: @arrived_distance)}km)
  = link_to '履歴を見る', arrivals_path, class: 'link-important ml-auto'