config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :walks do
    resources :arrivals, only: [:index], :to => 'walks/arrivals#index'
  end
  resources :arrivals, except: [:new] do
    resource :report, only: %i(show), controller: "arrivals/report"
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:destroy]
  devise_scope :user do
    post 'logout', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  # 以下の2つのルーティングはURLの修正に伴いリダイレクトさせているが、後に削除する
  scope module: 'tmp' do
    resources :users, only: [] do
      resources :arrivals, only: :index
    end
    get '/walk', to: 'walks#show'
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/views/layouts/_flash.html.slim
#flash
  - if flash[:notice]
    .bg-dark-blue-50.border-t.border-b.border-dark-blue-200.text-dark-blue-200.px-4.py-3
      = flash.notice
  - if flash[:alert]
    .bg-red-100.border-t.border-b.border-red-500.text-red-700.px-4.py-3
      = flash.alert

app/views/layouts/_footer.html.slim
footer.bg-white.border-t.border-gray-200.text-xs.text-center.pt-4.pb-3
  ul.flex.justify-center.items-center.pb-2
    li.inline-block.px-4.hover:underline.hover:text-gray-400 = link_to '利用規約', page_path('terms')
    li.inline-block.px-4.hover:underline.hover:text-gray-400 = link_to 'プライバシーポリシー', page_path('privacy')
    li.text-xl.px-4.hover:text-gray-400
      = link_to 'https://github.com/SuzukaHori/YamaNotes', target: '_blank', rel: 'noopener'
        i.fa-brands.fa-github
  ul.flex.justify-center.items-center
    li.px-4
      p.inline.pr-2 © 2024
      = link_to 'suzuka_hori', 'https://x.com/suzuka_hori', target: '_blank', rel: 'noopener', class: 'hover:underline hover:text-gray-400'

app/views/layouts/_google_analytics.html.slim
script[async src="https://www.googletagmanager.com/gtag/js?id=G-VQT4R8C8MZ"]
script
  | window.dataLayer = window.dataLayer || [];
  | function gtag(){dataLayer.push(arguments);}
  | gtag('js', new Date());
  | gtag('config', 'G-VQT4R8C8MZ');

app/views/layouts/_header.html.slim
header.bg-yamanote-green-100.flex.items-center.py-2.px-3.h-12.md:h-14.text-white
  = link_to current_walk ? walk_path(current_walk) : root_path do
    h1.flex.items-center.justify-center
      = image_tag 'logo_header.png', class: 'inline h-11 py-1 transition duration-200 ease-in-out md:py-0 hover:scale-95', alt: 'YamaNotesのロゴ'
  - if user_signed_in?
    .ml-auto data-controller='modal' data-action='click->modal#backdropClose'
      button.p-2.transition-all.duration-500.ease-out.rounded-lg.hover:bg-yamanote-green-200 data-action='modal#open' id='help_button'
        i.fa-solid.fa-circle-question.fa-xl
      = render partial: 'dialogs/help'
    div
      div data-controller='slideover' data-action="click->slideover#backdropClose"
        button#menu_button.transition-all.duration-500.ease-out.hover:bg-yamanote-green-200.rounded-lg.p-2 data-action='slideover#open'
          i.fa-solid.fa-bars.fa-xl
        = render partial: 'dialogs/menu'

app/views/layouts/application.html.slim
doctype html
html  class='text-base-black'
  head
    meta name='viewport' content='width=device-width,initial-scale=1'
    = display_meta_tags(default_meta_tags)
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'https://unpkg.com/leaflet@1.6.0/dist/leaflet.css',
      integrity: 'sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==',
      crossorigin: ''
    = include_gon
    = javascript_importmap_tags
    = favicon_link_tag('favicon.ico')
    = favicon_link_tag 'apple-touch-icon-180x180.png', rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png'
    - if params[:id].present? && current_page?(arrival_path(params[:id]))
      meta name='robots' content='noindex'
  body.bg-yamanote-green-50.max-w-screen-sm.mx-auto.min-h-screen.flex.flex-col
    - unless current_page?(root_path)
      = render partial: 'layouts/header', cached: true
    main.pb-2.flex-1.bg-white
      = render 'layouts/flash'
      .px-4
        = yield
    = render partial: 'layouts/footer', cached: true
    script[src='https://unpkg.com/leaflet@1.6.0/dist/leaflet.js'
      integrity='sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=='
      crossorigin='']
    script[async src="#{fontawesome_url}" crossorigin='']
    = render 'layouts/google_analytics'